# Load Data Dest

In [117]:
import pickle
x_test_a1= pickle.load(open("x_test\\x_test_a1.pickle", "rb"))
x_test_s1= pickle.load(open("x_test\\x_test_s1.pickle", "rb"))
x_test_a2= pickle.load(open("x_test\\x_test_a2.pickle", "rb"))
x_test_s2= pickle.load(open("x_test\\x_test_s2.pickle", "rb"))
x_test_a3= pickle.load(open("x_test\\x_test_a3.pickle", "rb"))
x_test_s3= pickle.load(open("x_test\\x_test_s3.pickle", "rb"))

y_test_a1= pickle.load(open("y_test\\y_test_a1.pickle", "rb"))
y_test_s1= pickle.load(open("y_test\\y_test_s1.pickle", "rb"))
y_test_a2= pickle.load(open("y_test\\y_test_a2.pickle", "rb"))
y_test_s2= pickle.load(open("y_test\\y_test_s2.pickle", "rb"))
y_test_a3= pickle.load(open("y_test\\y_test_a3.pickle", "rb"))
y_test_s3= pickle.load(open("y_test\\y_test_s3.pickle", "rb"))

### Hitung Jumlah Kemunculan Setiap Kelas pada Data Test

In [118]:
print('y_test_a1 : \n', y_test_a1.value_counts())
print('y_test_s1 : \n', y_test_s1.value_counts())
print('y_test_a2 : \n', y_test_a2.value_counts())
print('y_test_s2 : \n', y_test_s2.value_counts())
print('y_test_a3 : \n', y_test_a3.value_counts())
print('y_test_s3 : \n', y_test_s3.value_counts())

y_test_a1 : 
 1    353
0    227
Name: atraksi, dtype: int64
y_test_s1 : 
 1    323
0     30
Name: atraksi, dtype: int64
y_test_a2 : 
 0    384
1    196
Name: amenitas, dtype: int64
y_test_s2 : 
 1    126
0     70
Name: amenitas, dtype: int64
y_test_a3 : 
 0    512
1     68
Name: aksesibilitas, dtype: int64
y_test_s3 : 
 1    38
0    30
Name: aksesibilitas, dtype: int64


# Load Data Train Tanpa ROS

In [119]:
import pickle
x_train_a1= pickle.load(open("x_train\\x_train_a1.pickle", "rb"))
x_train_s1= pickle.load(open("x_train\\x_train_s1.pickle", "rb"))
x_train_a2= pickle.load(open("x_train\\x_train_a2.pickle", "rb"))
x_train_s2= pickle.load(open("x_train\\x_train_s2.pickle", "rb"))
x_train_a3= pickle.load(open("x_train\\x_train_a3.pickle", "rb"))
x_train_s3= pickle.load(open("x_train\\x_train_s3.pickle", "rb"))

y_train_a1= pickle.load(open("y_train\\y_train_a1.pickle", "rb"))
y_train_s1= pickle.load(open("y_train\\y_train_s1.pickle", "rb"))
y_train_a2= pickle.load(open("y_train\\y_train_a2.pickle", "rb"))
y_train_s2= pickle.load(open("y_train\\y_train_s2.pickle", "rb"))
y_train_a3= pickle.load(open("y_train\\y_train_a3.pickle", "rb"))
y_train_s3= pickle.load(open("y_train\\y_train_s3.pickle", "rb"))

### Hitung Jumlah Kemunculan Setiap Kelas pada Data Train RF tanpa ROS

In [120]:
print(' len y_train_a1 : \n', len(y_train_a1))
print('y_train_a1 : \n', y_train_a1.value_counts())
print('--------------------------------------------------')
print(' len y_train_s1 : \n', len(y_train_s1))
print('y_train_s1 : \n', y_train_s1.value_counts())
print('--------------------------------------------------')
print(' len y_train_a2 : \n', len(y_train_a2))
print('y_train_a2 : \n', y_train_a2.value_counts())
print('--------------------------------------------------')
print(' len y_train_s2 : \n', len(y_train_s2))
print('y_train_s2 : \n', y_train_s2.value_counts())
print('--------------------------------------------------')
print(' len y_train_a3 : \n', len(y_train_a3))
print('y_train_a3 : \n', y_train_a3.value_counts())
print('--------------------------------------------------')
print(' len y_train_s3 : \n', len(y_train_s3))
print('y_train_s3 : \n', y_train_s3.value_counts())

 len y_train_a1 : 
 2320
y_train_a1 : 
 1    1372
0     948
Name: atraksi, dtype: int64
--------------------------------------------------
 len y_train_s1 : 
 1372
y_train_s1 : 
 1    1237
0     135
Name: atraksi, dtype: int64
--------------------------------------------------
 len y_train_a2 : 
 2320
y_train_a2 : 
 0    1391
1     929
Name: amenitas, dtype: int64
--------------------------------------------------
 len y_train_s2 : 
 929
y_train_s2 : 
 1    600
0    329
Name: amenitas, dtype: int64
--------------------------------------------------
 len y_train_a3 : 
 2320
y_train_a3 : 
 0    2045
1     275
Name: aksesibilitas, dtype: int64
--------------------------------------------------
 len y_train_s3 : 
 275
y_train_s3 : 
 1    164
0    111
Name: aksesibilitas, dtype: int64


# Load Data Train dengan ROS

In [121]:
import pickle
x_train_a1_ROS= pickle.load(open("x_train ROS\\x_train_a1_ROS.pickle", "rb"))
x_train_s1_ROS= pickle.load(open("x_train ROS\\x_train_s1_ROS.pickle", "rb"))
x_train_a2_ROS= pickle.load(open("x_train ROS\\x_train_a2_ROS.pickle", "rb"))
x_train_s2_ROS= pickle.load(open("x_train ROS\\x_train_s2_ROS.pickle", "rb"))
x_train_a3_ROS= pickle.load(open("x_train ROS\\x_train_a3_ROS.pickle", "rb"))
x_train_s3_ROS= pickle.load(open("x_train ROS\\x_train_s3_ROS.pickle", "rb"))

y_train_a1_ROS= pickle.load(open("y_train ROS\\y_train_a1_ROS.pickle", "rb"))
y_train_s1_ROS= pickle.load(open("y_train ROS\\y_train_s1_ROS.pickle", "rb"))
y_train_a2_ROS= pickle.load(open("y_train ROS\\y_train_a2_ROS.pickle", "rb"))
y_train_s2_ROS= pickle.load(open("y_train ROS\\y_train_s2_ROS.pickle", "rb"))
y_train_a3_ROS= pickle.load(open("y_train ROS\\y_train_a3_ROS.pickle", "rb"))
y_train_s3_ROS= pickle.load(open("y_train ROS\\y_train_s3_ROS.pickle", "rb"))

### Hitung Jumlah Kemunculan Setiap Kelas pada Data Train RF tanpa ROS

In [122]:
print(' len y_train_a1_ROS : \n', len(y_train_a1_ROS))
print('y_train_a1_ROS : \n', y_train_a1_ROS.value_counts())
print('--------------------------------------------------')
print(' len y_train_s1_ROS : \n', len(y_train_s1_ROS))
print('y_train_s1_ROS : \n', y_train_s1_ROS.value_counts())
print('--------------------------------------------------')
print(' len y_train_a2_ROS : \n', len(y_train_a2_ROS))
print('y_train_a2_ROS : \n', y_train_a2_ROS.value_counts())
print('--------------------------------------------------')
print(' len y_train_s2_ROS : \n', len(y_train_s2_ROS))
print('y_train_s2_ROS : \n', y_train_s2_ROS.value_counts())
print('--------------------------------------------------')
print(' len y_train_a3_ROS : \n', len(y_train_a3_ROS))
print('y_train_a3_ROS : \n', y_train_a3_ROS.value_counts())
print('--------------------------------------------------')
print(' len y_train_s3_ROS : \n', len(y_train_s3_ROS))
print('y_train_s3_ROS : \n', y_train_s3_ROS.value_counts())

 len y_train_a1_ROS : 
 2744
y_train_a1_ROS : 
 0    1372
1    1372
dtype: int64
--------------------------------------------------
 len y_train_s1_ROS : 
 2474
y_train_s1_ROS : 
 0    1237
1    1237
dtype: int64
--------------------------------------------------
 len y_train_a2_ROS : 
 2782
y_train_a2_ROS : 
 0    1391
1    1391
dtype: int64
--------------------------------------------------
 len y_train_s2_ROS : 
 1200
y_train_s2_ROS : 
 1    600
0    600
dtype: int64
--------------------------------------------------
 len y_train_a3_ROS : 
 4090
y_train_a3_ROS : 
 0    2045
1    2045
dtype: int64
--------------------------------------------------
 len y_train_s3_ROS : 
 328
y_train_s3_ROS : 
 0    164
1    164
dtype: int64


# Ekstraksi Fitur

In [123]:
from sklearn.feature_extraction.text import TfidfVectorizer

def tfidf_vectorizer(x_train):
    vectorizer = TfidfVectorizer(sublinear_tf=True)
    vecx_train = vectorizer.fit_transform(x_train).toarray()
    return vecx_train, vectorizer

### Ekstraksi Fitur (TFIDF) Data Train RF tanpa ROS

In [124]:
x_train_a1_vect, vectorizer_a1 = tfidf_vectorizer(x_train_a1) 
x_train_s1_vect, vectorizer_s1 = tfidf_vectorizer(x_train_s1) 
x_train_a2_vect, vectorizer_a2 = tfidf_vectorizer(x_train_a2) 
x_train_s2_vect, vectorizer_s2 = tfidf_vectorizer(x_train_s2) 
x_train_a3_vect, vectorizer_a3 = tfidf_vectorizer(x_train_a3) 
x_train_s3_vect, vectorizer_s3 = tfidf_vectorizer(x_train_s3) 

In [125]:
def save_as_pkl(list_data, f_name):
    pickle.dump(list_data, open("TFIDF RF/" + f_name + ".pickle", "wb"))
    
save_as_pkl(vectorizer_a1.vocabulary_, 'TFIDF_a1')
save_as_pkl(vectorizer_a2.vocabulary_, 'TFIDF_a2')
save_as_pkl(vectorizer_a3.vocabulary_, 'TFIDF_a3')
save_as_pkl(vectorizer_s1.vocabulary_, 'TFIDF_s1')
save_as_pkl(vectorizer_s2.vocabulary_, 'TFIDF_s2')
save_as_pkl(vectorizer_s3.vocabulary_, 'TFIDF_s3')

### Ekstraksi Fitur (TFIDF) Data Train RF dengan ROS

In [126]:
x_train_a1_vect_ROS, vectorizer_a1_ROS = tfidf_vectorizer(x_train_a1_ROS) 
x_train_s1_vect_ROS, vectorizer_s1_ROS = tfidf_vectorizer(x_train_s1_ROS) 
x_train_a2_vect_ROS, vectorizer_a2_ROS = tfidf_vectorizer(x_train_a2_ROS) 
x_train_s2_vect_ROS, vectorizer_s2_ROS = tfidf_vectorizer(x_train_s2_ROS) 
x_train_a3_vect_ROS, vectorizer_a3_ROS = tfidf_vectorizer(x_train_a3_ROS) 
x_train_s3_vect_ROS, vectorizer_s3_ROS = tfidf_vectorizer(x_train_s3_ROS) 

In [127]:
def save_as_pkl(list_data, f_name):
    pickle.dump(list_data, open("TFIDF RF ROS/" + f_name + ".pickle", "wb"))
    
save_as_pkl(vectorizer_a1_ROS.vocabulary_, 'TFIDF_a1_ROS')
save_as_pkl(vectorizer_a2_ROS.vocabulary_, 'TFIDF_a2_ROS')
save_as_pkl(vectorizer_a3_ROS.vocabulary_, 'TFIDF_a3_ROS')
save_as_pkl(vectorizer_s1_ROS.vocabulary_, 'TFIDF_s1_ROS')
save_as_pkl(vectorizer_s2_ROS.vocabulary_, 'TFIDF_s2_ROS')
save_as_pkl(vectorizer_s3_ROS.vocabulary_, 'TFIDF_s3_ROS')

# Training Data

In [128]:
from sklearn.ensemble import RandomForestClassifier
def train_data(x_train_vect, y_train):
    model = RandomForestClassifier(random_state=42)
    model.fit(x_train_vect, y_train)
    return model 

### Training Data RF tanpa ROS

In [133]:
RFModel_a1=train_data(x_train_a1_vect,y_train_a1)
RFModel_s1=train_data(x_train_s1_vect,y_train_s1)
RFModel_a2=train_data(x_train_a2_vect,y_train_a2)
RFModel_s2=train_data(x_train_s2_vect,y_train_s2)
RFModel_a3=train_data(x_train_a3_vect,y_train_a3)
RFModel_s3=train_data(x_train_s3_vect,y_train_s3)

In [134]:
def save_as_pkl(list_data, f_name):
    pickle.dump(list_data, open("Model RF/" + f_name + ".pickle", "wb"))
    
save_as_pkl(RFModel_a1, 'RFModel_a1')
save_as_pkl(RFModel_s1, 'RFModel_s1')
save_as_pkl(RFModel_a2, 'RFModel_a2')
save_as_pkl(RFModel_s2, 'RFModel_s2')
save_as_pkl(RFModel_a3, 'RFModel_a3')
save_as_pkl(RFModel_s3, 'RFModel_s3')

### Training Data RF dengan ROS

In [135]:
RFModel_a1_ROS=train_data(x_train_a1_vect_ROS,y_train_a1_ROS)
RFModel_s1_ROS=train_data(x_train_s1_vect_ROS,y_train_s1_ROS)
RFModel_a2_ROS=train_data(x_train_a2_vect_ROS,y_train_a2_ROS)
RFModel_s2_ROS=train_data(x_train_s2_vect_ROS,y_train_s2_ROS)
RFModel_a3_ROS=train_data(x_train_a3_vect_ROS,y_train_a3_ROS)
RFModel_s3_ROS=train_data(x_train_s3_vect_ROS,y_train_s3_ROS)

In [136]:
def save_as_pkl(list_data, f_name):
    pickle.dump(list_data, open("Model RF ROS/" + f_name + ".pickle", "wb"))
    
save_as_pkl(RFModel_a1_ROS, 'RFModel_a1_ROS')
save_as_pkl(RFModel_s1_ROS, 'RFModel_s1_ROS')
save_as_pkl(RFModel_a2_ROS, 'RFModel_a2_ROS')
save_as_pkl(RFModel_s2_ROS, 'RFModel_s2_ROS')
save_as_pkl(RFModel_a3_ROS, 'RFModel_a3_ROS')
save_as_pkl(RFModel_s3_ROS, 'RFModel_s3_ROS')

# Pengujian Pickle Model

### memuat data test dengan vocabulary tfidf train pickle RF tanpa ROS

In [137]:
from sklearn.feature_extraction.text import TfidfVectorizer
saved_vocabulary_a1 = pickle.load(open("TFIDF RF\\TFIDF_a1.pickle", 'rb'))
tfidf_a1 = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_a1)

saved_vocabulary_a2 = pickle.load(open("TFIDF RF\\TFIDF_a2.pickle", 'rb'))
tfidf_a2 = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_a2)

saved_vocabulary_a3 = pickle.load(open("TFIDF RF\\TFIDF_a3.pickle", 'rb'))
tfidf_a3 = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_a3)

saved_vocabulary_s1 = pickle.load(open("TFIDF RF\\TFIDF_s1.pickle", 'rb'))
tfidf_s1 = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_s1)

saved_vocabulary_s2 = pickle.load(open("TFIDF RF\\TFIDF_s2.pickle", 'rb'))
tfidf_s2 = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_s2)

saved_vocabulary_s3 = pickle.load(open("TFIDF RF\\TFIDF_s3.pickle", 'rb'))  
tfidf_s3 = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_s3)

In [138]:
x_test_a1_vect= tfidf_a1.fit_transform(x_test_a1).toarray()
x_test_a2_vect= tfidf_a2.fit_transform(x_test_a2).toarray()
x_test_a3_vect= tfidf_a3.fit_transform(x_test_a3).toarray()
x_test_s1_vect= tfidf_s1.fit_transform(x_test_s1).toarray()
x_test_s2_vect= tfidf_s2.fit_transform(x_test_s2).toarray()
x_test_s3_vect= tfidf_s3.fit_transform(x_test_s3).toarray()

### memuat data test dengan vocabulary tfidf train pickle RF dengan ROS

In [139]:
from sklearn.feature_extraction.text import TfidfVectorizer
saved_vocabulary_a1_ROS = pickle.load(open("TFIDF RF ROS\\TFIDF_a1_ROS.pickle", 'rb'))
tfidf_a1_ROS = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_a1)
saved_vocabulary_a2_ROS = pickle.load(open("TFIDF RF ROS\\TFIDF_a2_ROS.pickle", 'rb'))
tfidf_a2_ROS = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_a2)
saved_vocabulary_a3_ROS = pickle.load(open("TFIDF RF ROS\\TFIDF_a3_ROS.pickle", 'rb'))
tfidf_a3_ROS = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_a3)
saved_vocabulary_s1_ROS = pickle.load(open("TFIDF RF ROS\\TFIDF_s1_ROS.pickle", 'rb'))
tfidf_s1_ROS = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_s1)
saved_vocabulary_s2_ROS = pickle.load(open("TFIDF RF ROS\\TFIDF_s2_ROS.pickle", 'rb'))
tfidf_s2_ROS = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_s2)
saved_vocabulary_s3_ROS = pickle.load(open("TFIDF RF ROS\\TFIDF_s3_ROS.pickle", 'rb'))  
tfidf_s3_ROS = TfidfVectorizer(sublinear_tf=True, vocabulary=saved_vocabulary_s3)

In [140]:
x_test_a1_vect_ROS= tfidf_a1_ROS.fit_transform(x_test_a1).toarray()
x_test_a2_vect_ROS= tfidf_a2_ROS.fit_transform(x_test_a2).toarray()
x_test_a3_vect_ROS= tfidf_a3_ROS.fit_transform(x_test_a3).toarray()
x_test_s1_vect_ROS= tfidf_s1_ROS.fit_transform(x_test_s1).toarray()
x_test_s2_vect_ROS= tfidf_s2_ROS.fit_transform(x_test_s2).toarray()
x_test_s3_vect_ROS= tfidf_s3_ROS.fit_transform(x_test_s3).toarray()

### Load pickle model RF tanpa ROS

In [141]:
import pickle
model_a1 = pickle.load(open('Model RF/RFModel_a1.pickle','rb'))
model_a2 = pickle.load(open('Model RF/RFModel_a2.pickle','rb'))
model_a3 = pickle.load(open('Model RF/RFModel_a3.pickle','rb'))
model_s1 = pickle.load(open('Model RF/RFModel_s1.pickle','rb'))
model_s2 = pickle.load(open('Model RF/RFModel_s2.pickle','rb'))
model_s3 = pickle.load(open('Model RF/RFModel_s3.pickle','rb'))

### Load pickle model RF dengan ROS

In [142]:
import pickle
model_a1_ROS = pickle.load(open('Model RF ROS/RFModel_a1_ROS.pickle','rb'))
model_a2_ROS = pickle.load(open('Model RF ROS/RFModel_a2_ROS.pickle','rb'))
model_a3_ROS = pickle.load(open('Model RF ROS/RFModel_a3_ROS.pickle','rb'))
model_s1_ROS = pickle.load(open('Model RF ROS/RFModel_s1_ROS.pickle','rb'))
model_s2_ROS = pickle.load(open('Model RF ROS/RFModel_s2_ROS.pickle','rb'))
model_s3_ROS = pickle.load(open('Model RF ROS/RFModel_s3_ROS.pickle','rb'))

In [146]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
from sklearn.metrics import balanced_accuracy_score
from imblearn.metrics import geometric_mean_score

def evaluate_model(model, vectorized_data, label):
    x_test = vectorized_data
    y_pred = model.predict(x_test)
    tp = np.sum(label * y_pred)
    fp = np.sum((label == 0) * y_pred)
    tn = np.sum((label==0) * (y_pred==0))
    fn = np.sum(label * (y_pred==0))
    print("True positive: ", tp)
    print("False negative: ", fn)
    print("False positive: ", fp)
    print("True negative: ", tn)
    print(metrics.confusion_matrix(label, y_pred))
    print(metrics.classification_report(label, y_pred))
    print("geometric_mean_score:",geometric_mean_score(label, y_pred))
    print("F-1Score:",metrics.f1_score(label, y_pred, average='macro'))
    print("balanced_accuracy_score:",balanced_accuracy_score(label, y_pred))

### Evaluasi model RF tanpa ROS

In [147]:
print('--------------------- MODEL A1 -------------------')
print(evaluate_model(model_a1, x_test_a1_vect, y_test_a1))
print('--------------------------------------------------')
print('--------------------- MODEL A2 -------------------')
print(evaluate_model(model_a2, x_test_a2_vect, y_test_a2))
print('--------------------------------------------------')
print('--------------------- MODEL A3 -------------------')
print(evaluate_model(model_a3, x_test_a3_vect, y_test_a3))
print('--------------------------------------------------')
print('--------------------- MODEL S1 -------------------')
print(evaluate_model(model_s1, x_test_s1_vect, y_test_s1))
print('--------------------------------------------------')
print('--------------------- MODEL S2 -------------------')
print(evaluate_model(model_s2, x_test_s2_vect, y_test_s2))
print('--------------------------------------------------')
print('--------------------- MODEL S3 -------------------')
print(evaluate_model(model_s3, x_test_s3_vect, y_test_s3))

--------------------- MODEL A1 -------------------
True positive:  325
False negative:  28
False positive:  53
True negative:  174
[[174  53]
 [ 28 325]]
              precision    recall  f1-score   support

           0       0.86      0.77      0.81       227
           1       0.86      0.92      0.89       353

    accuracy                           0.86       580
   macro avg       0.86      0.84      0.85       580
weighted avg       0.86      0.86      0.86       580

geometric_mean_score: 0.8400710592014632
F-1Score: 0.8501908488228598
balanced_accuracy_score: 0.8435998552370494
None
--------------------------------------------------
--------------------- MODEL A2 -------------------
True positive:  127
False negative:  69
False positive:  18
True negative:  366
[[366  18]
 [ 69 127]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89       384
           1       0.88      0.65      0.74       196

    accuracy                   

### Evaluasi model RF dengan ROS

In [148]:
print('--------------------- MODEL A1 ROS -------------------')
print(evaluate_model(model_a1_ROS, x_test_a1_vect_ROS, y_test_a1))
print('--------------------------------------------------')
print('--------------------- MODEL A2 ROS -------------------')
print(evaluate_model(model_a2_ROS, x_test_a2_vect_ROS, y_test_a2))
print('--------------------------------------------------')
print('--------------------- MODEL A3 ROS -------------------')
print(evaluate_model(model_a3_ROS, x_test_a3_vect_ROS, y_test_a3))
print('--------------------------------------------------')
print('--------------------- MODEL S1 ROS -------------------')
print(evaluate_model(model_s1_ROS, x_test_s1_vect_ROS, y_test_s1))
print('--------------------------------------------------')
print('--------------------- MODEL S2 ROS -------------------')
print(evaluate_model(model_s2_ROS, x_test_s2_vect_ROS, y_test_s2))
print('--------------------------------------------------')
print('--------------------- MODEL S3 ROS -------------------')
print(evaluate_model(model_s3_ROS, x_test_s3_vect_ROS, y_test_s3))

--------------------- MODEL A1 ROS -------------------
True positive:  299
False negative:  54
False positive:  23
True negative:  204
[[204  23]
 [ 54 299]]
              precision    recall  f1-score   support

           0       0.79      0.90      0.84       227
           1       0.93      0.85      0.89       353

    accuracy                           0.87       580
   macro avg       0.86      0.87      0.86       580
weighted avg       0.87      0.87      0.87       580

geometric_mean_score: 0.8724697869960316
F-1Score: 0.8635815196639939
balanced_accuracy_score: 0.8728519549238123
None
--------------------------------------------------
--------------------- MODEL A2 ROS -------------------
True positive:  146
False negative:  50
False positive:  32
True negative:  352
[[352  32]
 [ 50 146]]
              precision    recall  f1-score   support

           0       0.88      0.92      0.90       384
           1       0.82      0.74      0.78       196

    accuracy           